// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/adminLogin": {
            "post": {
                "description": "执行管理员登录操作",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "login"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "pwd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/administer/books": {
            "post": {
                "description": "添加图书的信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "添加图书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图书编号",
                        "name": "bn",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "书名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "描述",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "数量",
                        "name": "count",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "类别",
                        "name": "category",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/administer/books/page": {
            "get": {
                "description": "管理员浏览书籍",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "管理员浏览书籍",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "起始页码",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页记录数",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/administer/books/{id}": {
            "get": {
                "description": "获取一个图书的信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "获取图书信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "书籍id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            },
            "put": {
                "description": "修改图书信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "修改图书信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "书籍id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图书编号",
                        "name": "bn",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "书名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "描述",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "数量",
                        "name": "count",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "类别",
                        "name": "category",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除图书",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "删除图书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "书籍id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/administer/categories": {
            "get": {
                "description": "获取分类",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "获取分类",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            },
            "post": {
                "description": "添加分类",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "添加分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分类名",
                        "name": "category",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/administer/categories/{id}": {
            "put": {
                "description": "修改分类",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "修改分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分类名",
                        "name": "category",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除分类",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "删除分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/administer/records": {
            "get": {
                "description": "查看所有记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "查看所有记录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/administer/records/{status}": {
            "get": {
                "description": "查看所有归还或未归还记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "查看所有归还或未归还记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/administer/users": {
            "get": {
                "description": "管理员获取用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "管理员获取用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/administer/users/{id}": {
            "put": {
                "description": "管理员修改用户信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "管理员修改用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "旧密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新密码",
                        "name": "newpassword",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "电话",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            },
            "delete": {
                "description": "管理员删除用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "管理员删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/administer/users/{id}/records/{status}": {
            "get": {
                "description": "管理员信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminstr"
                ],
                "summary": "管理员查看借书信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图书状态",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/books": {
            "get": {
                "description": "游客浏览书籍",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tourist"
                ],
                "summary": "游客浏览书籍",
                "parameters": [
                    {
                        "type": "string",
                        "description": "起始id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "每页书籍数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "游客浏览分类",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tourist"
                ],
                "summary": "游客浏览分类",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/codelogin": {
            "post": {
                "description": "执行登录操作",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "login"
                ],
                "summary": "验证码登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "yzm",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/sendcode": {
            "get": {
                "description": "用户登录页获取验证码操作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "获取验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/userLogin": {
            "post": {
                "description": "执行用户登录操作",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "login"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "pwd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "用户查看自己信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户查看信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            },
            "post": {
                "description": "用户注册",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "昵称",
                        "name": "userName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "性别",
                        "name": "sex",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "电话号码",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/users/books/page": {
            "get": {
                "description": "用户浏览书籍",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户浏览书籍",
                "parameters": [
                    {
                        "type": "string",
                        "description": "起始id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "每页书籍数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/users/books/{id}": {
            "get": {
                "description": "获取一个图书的信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "获取图书信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "书籍id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/tools.HttpCode"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Book"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/categories/{id}": {
            "get": {
                "description": "根据种类id查找书籍",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "根据分类id查书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "书籍种类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/users/records/{bookid}": {
            "put": {
                "description": "还书",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "还书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "书籍id",
                        "name": "bookid",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            },
            "post": {
                "description": "借书",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "借书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "书籍id",
                        "name": "bookid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "\"2006-01-02 15:04:05\"",
                        "description": "借书截至时间",
                        "name": "time",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "put": {
                "description": "用户修改自己的信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户修改信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "旧密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新密码",
                        "name": "newpassword",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "电话",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tools.HttpCode"
                        }
                    }
                }
            }
        },
        "/users/{id}/records": {
            "get": {
                "description": "获取用户借书记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "获取借书记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/tools.HttpCode"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Book"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/{id}/records/{status}": {
            "get": {
                "description": "获取用户还书记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "获取还书记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图书状态",
                        "name": "status",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/tools.HttpCode"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Book"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Book": {
            "type": "object",
            "properties": {
                "bn": {
                    "description": "图书编号",
                    "type": "string"
                },
                "classificationId": {
                    "description": "分类id",
                    "type": "integer"
                },
                "count": {
                    "description": "数量 默认为1",
                    "type": "integer"
                },
                "description": {
                    "description": "图书描述",
                    "type": "string"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "img_Url": {
                    "description": "图片地址",
                    "type": "string"
                },
                "name": {
                    "description": "图书名",
                    "type": "string"
                }
            }
        },
        "tools.HttpCode": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "图书管理系统API",
	Description:      "该项目为本人独立开发的小项目",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
